- modi/_can_process.py
- modi/_can_task.py
- modi/_executor_task.py
- modi/modi.py
Includes features,
1. separate the threads of reading/writing can communication messages
> Fix bug in Feature/multi threaded can task

- modi/_can_process.py
- modi/_can_task.py
- modi/_executor_task.py
- modi/_executor_thread.py
- modi/modi.py
Includes features,
1. Create initializing threading event object
2. Control the synchronization between parent and child thread
> Implement feature/multi-threaded-can-task

- modi/_can_task.py
- modi/_communicator.py
- modi/_communicator_task.py
- modi/_ser_task.py
Fix bugs,
1. Fix multi processing issues in Windows platform.
2. Rearrange method interfaces of '_communicator_task.py'.
> Fix bugs in feature/threaded-serial-task

- modi/_ble_task.py
- modi/_communicator.py
- modi/_executor_task.py
- modi/modi.py
Errors include,
1.  Re-initializing hci interface for re-scanning.
2. Add BLE exception handling.
> Fix errors in feature/enable-ble

- CODE_OF_CONDUCT.md
- MANIFEST.in
- README.md
1. Add CODE_OF_CONDUCT.md adapted from contributor covenant
2. Add Contribution Guidelines section to README.md
3. Add API Document badge to README.md
4. Add a table for system build support to README.md
> Add system support and code of conduct to README.md

- modi/module/input_module/button.py
- modi/module/input_module/dial.py
- modi/module/input_module/env.py
- modi/module/input_module/gyro.py
- modi/module/input_module/ir.py
- modi/module/input_module/mic.py
- modi/module/input_module/ultrasonic.py
- modi/module/module.py
- modi/module/output_module/display.py
- modi/module/output_module/led.py
- modi/module/output_module/motor.py
- modi/module/output_module/speaker.py
1. Add and fix docstring to output modules
2. Add and fix docstring to input modules
> Add docstring to modules

- modi/_conn_proc.py
- modi/_exe_thrd.py
- modi/modi.py
- modi/task/can_task.py
- modi/task/conn_task.py
- modi/task/exe_task.py
- modi/task/ser_task.py
- modi/task/spp_task.py
1. Add docstring to methods in procedures
2. Add docstring to methods in treads
3. Add docstring to methods in tasks
4. Add docstring and type annotations to modi.py
> Add docstring to tasks, process and thread

- docs/conf.py
- modi/__init__.py
- setup.py
1. Add encoding specification of utf8 to __init__
2. Add encoding specification of utf8 to conf.py
3. Add encoding specification of utf8 to setup.py
> Add utf8 encoding specification

- modi/modi.py
- requirements.txt
- tests/test_modi.py
1. Add print_topology_matrix method of printing adjacency matrix
2. Add print_topology_map method of printing topology tree
> Refactor topology map

- modi/modi.py
- tests/test_modi.py
1. Add print_topology_map method that prints out the topology of the connected modules
> Implement print topology map function

- modi/_conn_proc.py
- modi/modi.py
- modi/task/ser_task.py
1. Add thread to keep track of child thread of connection process
2. Add exception handling to exit when the child process raises an exception
> Add exception handling for connection process

- modi/task/ser_task.py
1. Print traceback information when the connection is lost
> Fix error message in serial exception handling

- modi/modi.py
1. Add windows exception handling of multiprocessing
> Fix windows exception of multiprocessing

- README.md
> Add uml diagram to readme

- modi/module/input_module/button.py
- modi/module/input_module/dial.py
- modi/module/input_module/env.py
- modi/module/input_module/gyro.py
- modi/module/input_module/ir.py
- modi/module/input_module/mic.py
- modi/module/input_module/ultrasonic.py
- modi/module/module.py
- modi/module/output_module/display.py
- modi/module/output_module/led.py
- modi/module/output_module/motor.py
- modi/module/output_module/output_module.py
- modi/module/output_module/speaker.py
- modi/module/setup_module/network.py
- modi/task/exe_task.py
- tests/module/output_module_tests/test_display.py
- tests/module/output_module_tests/test_led.py
- tests/module/output_module_tests/test_motor.py
- tests/module/output_module_tests/test_speaker.py
1. Fix enum typed property_types to intenum
2. Fix value calls of enum objects to direct calls to itself
> Fix property types to intenum

- examples/button_example.py
- examples/dial_example.py
- examples/display_example.py
- examples/env_example.py
- examples/gyro_example.py
- examples/ir_example.py
- examples/led_example.py
- examples/mic_example.py
- examples/motor_example.py
- examples/speaker_example.py
- examples/ultrasonic_example.py
1. Add examples directory on the top-level directory
2. Add sample scripts for the usage of each module
> Add example script for each module

- modi/modi.py
- modi/module/output_module/display.py
- modi/module/output_module/led.py
- modi/module/output_module/motor.py
- modi/module/output_module/speaker.py
- tests/module/output_module_tests/test_display.py
- tests/module/output_module_tests/test_led.py
- tests/module/output_module_tests/test_motor.py
- tests/module/output_module_tests/test_speaker.py
1. Separate set_methods and get_methods
2. Implement get methods for output modules
3. Fix tests for output modules accordingly 
4. Add type annotations for methods
5. Fix exception handling for modi multi-processing runtime error
>  Implement get methods for output modules

- README.md
1. Center the uml diagram
2. Remove table around badges
> Refactor readme document

- .githooks/pre-commit
- .githooks/pre-push
- tox.ini
1. Add git hook pre-commit to run flake8 before committing
2. Add git hook pre-push to prevent direct pushes to master and develop branches
> Add .githooks

- modi/__init__.py
- modi/_conn_proc.py
- modi/module/module.py
- modi/module/output_module/display.py
- modi/module/output_module/led.py
- modi/module/output_module/motor.py
- modi/module/output_module/speaker.py
- modi/task/exe_task.py
- modi/task/spp_task.py
- modi/util/that.py
- modi/util/topology_manager.py
- tests/module/output_module_tests/test_motor.py
- tests/task/test_can_task.py
- tests/task/test_conn_task.py
- tests/task/test_exe_task.py
- tests/task/test_ser_task.py
1. Refactor every script that fails flake8 test
> Refactor scripts to pass flake8 convention test

- .githooks/pre-commit
1. Replace pre-commit hook to python script integrating the flake8 git library
> Fix pre-commit hook to python flake8 script

- modi/_conn_proc.py
- modi/_exe_thrd.py
- modi/modi.py
1. Add thread and process event to control the modi initialization
> Add thread and process event to optimize modi initialization time

- modi/_conn_proc.py
- modi/task/can_task.py
- modi/task/conn_task.py
- modi/task/ser_task.py
- modi/task/spp_task.py
- tests/task/test_ser_task.py
- tests/task/test_spp_task.py
1. Rename read/write to recv/send
> Rename read/write to recv/send

- .githooks/pre-commit
- modi/modi.py
- modi/module/module.py
- modi/task/exe_task.py
- modi/util/firmware_updater.py
1. Fix scripts based on pep8 convention
2. Change the path to binary os using f-string
3. Add progress bar for the update method
4. Remove unnecessary features from module updater
5. Fix a bug of adding processed module to a waitlist
6. Add docstring and type annotations to methods in the module updater
> Refactor module firmware updater

- modi/util/tutor.py
1. Move all the helper function into the tutor class
> Refactor tutor class to remove all the outer helper functions

- modi/module/output_module/display.py
- modi/module/output_module/led.py
- modi/module/output_module/motor.py
- modi/module/output_module/output_module.py
- modi/module/output_module/speaker.py
- tests/module/output_module_tests/test_display.py
- tests/module/output_module_tests/test_led.py
- tests/module/output_module_tests/test_speaker.py
1. Refactor set_property to separate parse_msg method
2. Fix unit tests accordingly
> Refactor set property

- examples/creation_examples/brush.py
- examples/creation_examples/dodge.py
- examples/creation_examples/galaga.py
- examples/creation_examples/modimouse.py
- examples/usage_examples/button_example.py
- examples/usage_examples/dial_example.py
- examples/usage_examples/display_example.py
- examples/usage_examples/env_example.py
- examples/usage_examples/gyro_example.py
- examples/usage_examples/ir_example.py
- examples/usage_examples/led_example.py
- examples/usage_examples/mic_example.py
- examples/usage_examples/motor_example.py
- examples/usage_examples/speaker_example.py
- examples/usage_examples/ultrasonic_example.py
1. Add creation examples
2. Refactor examples directory
> Add creation examples

- .travis.yml
- README.md
- setup.py
- tox.ini
1. Fix travis error of not locating python interpreter
> Use pyenv on travis

- .travis.yml
- README.md
- examples/creation_examples/rand_croc.py
- modi/modi.py
- modi/module/output_module/led.py
- modi/module/output_module/output_module.py
- modi/task/exe_task.py
- modi/util/misc.py
- setup.py
- tests/module/output_module_tests/test_led.py
- tests/test_modi.py
- tox.ini
1. Change behaviors of set_red, set_blue, set_green methods of led module
2. Add 0.1 seconds of delay after set property
> Fix set_property methods of led module

- README.md
1. Change the image address of pymodi logo
2. Renew the permalink of uml diagram
> Refactor readme.md

- modi/__main__.py
- modi/modi.py
1. Remove waiting feature if nb_modules argument is not given
> Add lazy initialization feature

- .travis.yml
Features include
1. Change travis lifecycle to install pyenv before script
> Change lifecycle for macos test

- modi/_exe_thrd.py
- modi/modi.py
- modi/module/module.py
- modi/task/exe_task.py
- modi/util/firmware_updater.py
- modi/util/topology_manager.py
1. Refactor code based on pep8 convention
2. Fix print topology map method error
> Refactor code to pass convention tests

- modi/modi.py
- modi/util/queues.py
1. Create communication queue for communication
2. Change recv and send queue to priority queue
> Add multiprocessing priority queue

- .githooks/pre-push
- tox.ini
1. Change prepush githook to run tox on local environments
2. Add python3.6~3.8 to tox envlist
> Fix prepush to run tox on local environment

- modi/_conn_proc.py
- modi/modi.py
- modi/task/ser_task.py
1. Refactor ser_task to support connection with more than one network modules
> Refactor code to support multiple network modules

- examples/creation_examples/galaga.py
1. Create simplified galaga example
> Make simplified galaga example

- modi/modi.py
1. Add global list of conn_procs to properly terminate them
2. Terminate subprocesses at os._exit
> Fix a bug of subprocess being alive after main process is terminated

- .github/workflows/coverage.yml
1. Change trigger condition for coverage action to pull request
> Change trigger for coverage to pull request

- modi/modi.py
1. Add additional exception handling of process lookup error
> Add additional exception handling of lookup error

- examples/usage_examples/multi_module_example.py
- modi/_exe_thrd.py
- modi/modi.py
- modi/module/module.py
- modi/module/output_module/led.py
- modi/task/exe_task.py
- modi/util/misc.py
- modi/util/queues.py
- modi/util/topology_manager.py
1. Enable getting the module based on the module id
2. Fix the order at which modules are sorted in getter method
> Change module getter to return modules in order

- .github/workflows/convention.yml
- .github/workflows/coverage.yml
- .github/workflows/deploy.yml
1. Send an email notification when the package is deployed
> Add send email action to deploy workflow

- modi/__main__.py
- modi/util/topology_manager.py
1. Fix an error that the modi initialization never ends when only one module is connected
> Fix an error in which modi initialization does not end

- modi/modi.py
- modi/module/output_module/led.py
- modi/module/output_module/motor.py
- modi/module/output_module/output_module.py
- modi/module/output_module/speaker.py
- tests/module/output_module_tests/test_led.py
- tests/module/output_module_tests/test_motor.py
- tests/module/output_module_tests/test_speaker.py
1. Refactor output modules using decorator
2. Create a decorator in the output module class
> Refactor output modules using decorator

- modi/__main__.py
- modi/modi.py
- modi/module/module.py
- modi/module/output_module/display.py
- modi/module/output_module/output_module.py
- modi/task/exe_task.py
- modi/util/msgutil.py
- modi/util/queues.py
- tests/module/input_module_tests/test_button2.py
- tests/task/test_exe_task.py
1. Create message util feature and methods for message handling
2. Refactor output module using message util methods
3. Add automatic performance test for modi __main__
4. Add low-level send and recv method for modi
> Create message util feature

- modi/modi.py
1. Remove unused import of json
> Remove unused import of json

- .github/workflows/deploy.yml
1. Fix a trigger condition for the deployment to the creation of release tag
> Fix deployment github action

- modi/task/can_task.py
- tests/task/test_can_task.py
> Add can task test

- .githooks/commit-msg
- .githooks/pre-commit
- .githooks/prepare-commit-msg
> Add commit-msg githook to check non-english commit message

- modi/_exe_thrd.py
- modi/modi.py
- modi/task/exe_task.py
- modi/util/topology_manager.py
1. Fix an error in which topology map is not printed properly
> Fix topology print error

- .githooks/commit-msg
- modi/util/misc.py
- modi/util/topology_manager.py
1. Fix topology manager to print out module index
> Fix topology manager to print out module index

- requirements_dev.txt
> Add m2r to requirements_dev

- docs/modi.module.input_module.rst
- docs/modi.module.output_module.rst
- docs/modi.module.rst
- docs/modi.module.setup_module.rst
- docs/modi.rst
- docs/modi.task.rst
- docs/modi.util.rst
> Refactor rst documents

- README.md
> Add line below logo

- .github/workflows/deploy.yml
- README.md
1. Fix doc status badge on readme
> Fix readme badge for docs

- .github/workflows/deploy.yml
- README.md
> Remove redundant RtD workflow

- .github/workflows/deploy.yml
> Enable negative inputs to motor's speed method

- HISTORY.md
> Update an entry in History.md

- setup.py
> Update keyword for PyPI information

- .github/workflows/deploy.yml
> Add skip-existing flag to upload existing version package

- modi/module/output_module/motor.py
- modi/util/msgutil.py
- tests/module/output_module_tests/test_motor.py
Fix motor error that it does not handle negative speed
> Fix motor error that it does not handle negative speed

- modi/module/module.py
- modi/task/exe_task.py
> Add feature to check version

- .github/workflows/deploy.yml
Create automated release workflow
> Create automated release workflow

- .github/workflows/deploy.yml
Add bumpversion checking feature
> Add bumpversion checking feature

- CONTRIBUTING.md
- README.md
Fix image links to absolute path
> Fix image links to absolute path

- .github/workflows/deploy.yml
> Add develop pull request

- .github/workflows/deploy.yml
Fix release message on notifications
> Fix release message on notifications

- index.html
Remove korean form pymodi page
> Remove korean form pymodi page

- modi/__init__.py
- modi/module/module.py
- modi/task/exe_task.py
- modi/task/ser_task.py
Check health message for user code
> Check health message for user code

- modi/module/module.py
- modi/task/can_task.py
- modi/task/exe_task.py
- modi/task/ser_task.py
- modi/util/topology_manager.py
1. Fix connection tasks to wait only when there is nothing to send or recv
2. Fix update health method to only request when id is recognizable
> Fix can connection error

- modi/task/exe_task.py
Enable adaptive update of topology
> Enable adaptive update of topology

- modi/task/ser_task.py
Fix an error that log is not redirected
> Fix an error that log is not redirected

- modi/_conn_proc.py
> Fix init task method

- modi/task/can_task.py
- tests/task/test_can_task.py
> Fix singleton can-task

- AUTHORS.md
> Include Sebeom as a maintainer

- modi/__init__.py
> Implement a feature which checks the running python version

- README.md
Update features section of readme
> Update features section of readme

- index.html
- modules_en.html
Change default language based on the page
> Change default language based on the page

- modi/task/ser_task.py
- tests/task/test_ser_task.py
Redactor serial task using read_until method
> Refactor serial task using read_until method

- modi/module/module.py
- modi/task/can_task.py
- modi/task/conn_task.py
- modi/task/exe_task.py
- modi/task/ser_task.py
- modi/util/firmware_updater.py
Fix module importing convention
> Fix module importing convention

- modules_en.html
- modules_kr.html
> Add id to module sections

- modi/util/stranger.py
- modi/util/topology_manager.py
Refactor codes considering maintainability
> Refactor codes considering maintainability

- CONTRIBUTING.md
- README.md
> Fix image failing url

- CONTRIBUTING.md
- README.md
Add language specification to code blocks
> Add language specification to code blocks

- modi/module/output_module/led.py
- modi/module/output_module/motor.py
- modi/module/output_module/speaker.py
- tests/module/output_module_tests/test_speaker.py
Update properties when setting property
> Update properties when setting property

- modi/task/exe_task.py
Send pnp off message when pnp is on
> Send pnp off message when pnp is on

- modi/modi.py
- modi/module/module.py
- modi/util/misc.py
- tests/test_modi.py
> Remove lazy getting feature

- examples/creation_examples/galaga.py
> Fix galaga example

- modi/firmware_updater.py
- modi/module/module.py
- modi/task/exe_task.py
- modi/util/misc.py
> Fix stm updater malfunction

- README.md
- modi/__init__.py
- modi/__main__.py
- modi/_conn_proc.py
- modi/_exe_thrd.py
- modi/firmware_updater.py
- modi/modi.py
- modi/module/module.py
- modi/task/can_task.py
- modi/task/conn_task.py
- modi/task/exe_task.py
- modi/task/ser_task.py
- modi/util/misc.py
- modi/util/msgutil.py
- modi/util/queues.py
- modi/util/stranger.py
- modi/util/topology_manager.py
- tests/task/test_can_task.py
- tests/task/test_ser_task.py
> Refactor codes based on pep8

- modi/util/msgutil.py
- setup.py
> Refactor for maintainability

- modi/__init__.py
> Add timeout to version check

- modi/__init__.py
- modi/module/module.py
- modi/task/exe_task.py
> Remove version check

- modi/module/input_module/input_module.py
- modi/module/module.py
- modi/module/output_module/output_module.py
- modi/task/exe_task.py
Avoid sending same set messages
> Avoid sending same set messages

- modi/debugger.py
Add feature to select certain command
> Add feature to select certain command

- modi/module/module.py
- modi/task/exe_task.py
Add a property of checking the version of module
> Add a property of checking the version of module

- modi/modi.py
- modi/module/module.py
- modi/task/exe_task.py
- modi/util/misc.py
Change import setting to speed up import
> Change import setting to speed up import

- modi/debugger.py
- modi/module/module.py
- modi/module/output_module/led.py
- modi/module/output_module/motor.py
- modi/module/output_module/output_module.py
- modi/module/output_module/speaker.py
- modi/task/ser_task.py
- tests/module/output_module_tests/test_led.py
- tests/module/output_module_tests/test_speaker.py
- tests/task/test_ser_task.py
Implement redundancy check for setters
> Implement redundancy check for setters

- modi/__init__.py
- modi/firmware_updater.py
- modi/modi.py
- modi/task/exe_task.py
- modi/task/ser_task.py
1. Add update methods at top module
2. Change update guide message
> Add update methods at top module

- modi/modi.py
- modi/util/topology_manager.py
Add timeout to modi initialization
> Add timeout to modi initialization

- modi/modi.py
> Remove checking invalid key

- modi/modi.py
- modi/task/ble_task_pi.py
- modi/task/exe_task.py
> Enable ble task for pi

- modi/modi.py
- modi/module/output_module/output_module.py
- modi/module/setup_module/network.py
- modi/task/exe_task.py
Enable integration with modi play
> Enable integration with modi play

- modi/module/setup_module/network.py
> Fix bug related to buzzer on

- modi/module/output_module/output_module.py
- modi/module/setup_module/network.py
- modi/task/ble_task.py
- modi/task/can_task.py
- modi/task/conn_task.py
- modi/task/ser_task.py
Fix send methods to wait after writing
> Fix send methods to wait after writing

- modi/debugger.py
> Fix debugger spec

- examples/creation_examples/motor_play.py
> Add ble car example

- modi/__main__.py
- modi/module/module.py
> Fix module ordering method

- index.html
> Add car gif

- modi/__main__.py
> Fix performance test

- modi/firmware_updater.py
> Fix a pycharm thread progress bar issue

- modi/module/output_module/led.py
> PYM-16 Fix red, blue, green methods

- modi/module/output_module/speaker.py
- tests/module/output_module_tests/test_speaker.py
> PYM-5 Refactor speaker module

- modi/firmware_updater.py
> Enable stm update through can

- modi/modi.py
- modi/util/upython.py
- requirements.txt
> Implement ampy upload method

- modi/firmware_updater.py
- modi/modi.py
- modi/module/module.py
- modi/module/output_module/speaker.py
- modi/task/exe_task.py
Advise the user to reset the module if user code is in it
> Advise user to reset the module if user code is in it

- modi/firmware_updater.py
- modi/modi.py
Add feature to reset module firmware
> Add feature to reset module firmware

- modi/modi.py
Update modules that are not up to date
> Update modules that are not up to date

- modi/__init__.py
- modi/firmware_updater.py
- modi/module/setup_module/network.py
- modi/task/exe_task.py
> Add esp version check

- modi/firmware_updater.py
- modi/task/can_task.py
- modi/task/ser_task.py
> Fix stm updater timing issue

- modi/modi.py
Remove user code check if conn mode is ble
> Remove user code check if conn mode is ble

- modi/firmware_updater.py
> Fix time.time to time.clock

- modi/firmware_updater.py
> Fix wait time to 0.002 s

- modi/firmware_updater.py
> Fix esp updater progress bar

- modi/firmware_updater.py
Fix time.clock to time.perf_counter
> Fix time.clock to time.perf_counter

- modi/__main__.py
- modi/modi.py
- modi/task/ble_task.py
> Add retry to connection

- modi/task/ble_task.py
Add exception handling of post close
> Add exception handling of post close

- modi/modi.py
- modi/task/ble_task.py
> Block ble on macOS

- modi/task/can_task.py
- modi/task/exe_task.py
Reset can task instances when closing
> PYM-18 Reset can task instances when closing

- modi/firmware_updater.py
- requirements.txt
> Fix network firmware updater

- modi/modi.py
> Refactor filepath for RPI BLE in modi.py

- CONTRIBUTING.md
- modi/module/module.py
- tests/module/input_module_tests/test_button.py
- tests/module/input_module_tests/test_dial.py
- tests/module/input_module_tests/test_env.py
- tests/module/input_module_tests/test_gyro.py
- tests/module/input_module_tests/test_ir.py
- tests/module/input_module_tests/test_mic.py
- tests/module/input_module_tests/test_ultrasonic.py
- tests/module/output_module_tests/test_display.py
- tests/module/output_module_tests/test_led.py
- tests/module/output_module_tests/test_motor.py
- tests/module/output_module_tests/test_speaker.py
> Reduce sampling rate to 0.1 second

- README.md
> Add promotion video to REAMDE.md

- .github/workflows/convention.yml
- HISTORY.md
Regarding GITHUB_TOKEN, see
https://docs.github.com/en/actions/reference/authentication-in-a-workflow
> Add code style check using autopep8

- index.html
Update the blog site, index.html usage part.
Add modal, module's information, code block for usage.
> Update index.html usage part

- editor.html
- js/demo.js
- js/simple-console.js
> Update console and build console-module connection

- modi/modi.py
- modi/task/soc_task.py
- requirements.txt
PyMODI now supports communication over websocket.
None.
> Implement websocket server for pymodi

- modi/modi.py
- modi/task/ble_task/ble_task_mac.py
- requirements.txt
> Fix duplicate ble connection for macOS

- .github/workflows/release.yml
- Dockerfile
1. Automate ghcr uploading in the release event
2. Automate labelling process of docker image to pymodi repository
None.
> Enhance docker support

- modi/modi.py
- modi/task/ble_task/ble_task_mac.py
New features include,
1. Detach GUI Firmware Updater from PyMODI 
To another [Repo](https://github.com/luxrobo/modi-firmware-updater).
2. Implement web client connection for PyMODI 
PyMODI can now work as a web client, this makes MODI open for control over the internet.
3. Package PyMODI into Dockerfile
PyMODI is now packaged into a docker file via GHCR.
> Fix convention according to flake8
